services:
  - type: web
    name: pte-mobile-weather-app
    env: static
    buildCommand: cd pte-mobile-app && npm ci && npm run build
    staticPublishPath: pte-mobile-app/build
    pullRequestPreviewsEnabled: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
